### PR TITLE
install dependencies and save to requirements.txt

### PR DESCRIPTION
**Pull request by StephanieQuon**

### CODE REVIEW

**Review by bradwbradw — CHANGES_REQUESTED** [review]
Hey @StephanieQuon, it looks like the existing requirements were overwritten when doing pip freeze. This is probably because the existing dependencies had not been installed when you ran freeze. Here's how you can fix:

- rename the new requirements.txt to requirements2.txt
- revert the commit ( or just get back original requirements.txt contents by copy/paste, etc)
- ensure the environment is active (if using venv)
- run `pip install -r requirements.txt` so that the existing dependencies are installed into the environment
- run `pip install -r requirements2.txt to install the new deps
- run the freeze command and save as requirements.txt 
- delete requirements2.txt

**Review by bradwbradw — COMMENTED** [review]
I also find it unusual that Flask is included, is that something you use in other python projects on your computer?

**Comment by bradwbradw** [comment]
I'd like to make sure you are using `venv` for this task. Sorry that wasn't as clear in the ticket description, otherwise the requirements will list all packages installed in the computer, not just packages we need for variome.

Before running any pip commands, please check the output of `which pip`. The result should be inside the repository directory for any pip install / freeze commands to work properly. 

If it's not, you'll need to create and then activate the virtual environment (https://towardsdatascience.com/getting-started-with-python-virtual-environments-252a6bd2240)

I would use `variome-env` as the name, rather than `venv`

(in the root of variome directory)
`python3 -m venv variome-env` or `python -m venv variome-env`

then, 

`source ./variome-env/bin/activate`

then, the result of `which pip` should point to inside the bin folder in the project's environment

**Comment by bradwbradw** [comment]
👍👍👍

**Comment by StephanieQuon** [comment]
Apologies for just following up with a comment now! Thank you so much for the detailed instructions and feedback, I really appreciate it and it was super helpful!!

**Pull request merged**
